##Installing all R dependencies

install.packages("devtools")
devtools::install_github('hadley/ggplot2')
install.packages("data.table")
install.packages("plyr")
install.packages("dplyr")
install.packages("openxlsx")
install.packages("yaml")
install.packages("shiny")
install.packages("lubridate")
install.packages("wordcloud")
install.packages("stringr")
install.packages("tm")
install.packages("SnowballC")
install.packages("RColorBrewer")
install.packages("pander")
install.packages("plotly")
install.packages("tibble")
install.packages("markdown")
install.packages("googleVis")
install.packages("RMySQL")
install.packages("DT")