--- 
security: 
  tokenSlack: xoxp-3633760318-3633833010-238631105570-2e5fb4cbe9f2b60f484bd047a25c0381
  tokenNicobot: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  zipMdp: rien
  zipUser: rien
  zipURL: http://zqsd.be/rien/message.zip
  dbMdp: dev  