--- 
security: 
  tokenSlack: xoxp-3633760318-3633833010-184980579172-6974251112d773ed6946038d2d773dd1
  tokenNicobot: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  zipMdp: rien
  zipUser: rien
  zipURL: http://zqsd.be/rien/message.zip
  dbMdp: dev  