--- 
security: 
  tokenSlack: xoxp-3633760318-3633833010-238654188322-b654a366ef45a48c1cded9f6cad8c399
  tokenNicobot: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  zipMdp: rien
  zipUser: rien
  zipURL: http://zqsd.be/rien/message.zip
  dbMdp: gnitroperdsqz  